version: '3.8'

services:
  api:
    build: .
    container_name: doctor_api
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: always
    command: npm start  # or nodemon if you're using it in dev

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
